# SEE SCRIPTS IN `tools/` DIRECTORY

db:
  configs:
    jdbc-url: jdbc:mysql://localhost:3306/comparison_configs
    username: root
    password: root
    maximum-pool-size: 10
    test-on-borrow: true

  auditresults:
    jdbc-url: jdbc:mysql://localhost:3306/comparison_results
    username: root
    password: root
    maximum-pool-size: 10

  webjourneyresults:
    jdbc-url: jdbc:mysql://localhost:3306/comparison_webjourneyresults
    username: root
    password: root
    maximumPoolSize: 10

observepoint:
  app-api-url: "localhost:8088"

cloud:
  aws:
    credentials:
      access-key: ""
      secret-key: ""
    sfn:
      comparison-one-time-state-machine-arn: ""
